debug: true
server.port: 8081

# mybatis config
mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath*:com/enlink/redisdic/dao/mapper/xml/*Mapper.xml
    type-aliases-package: com.enlink.redisdic.dao.entity
    # 性能监测设定的数据库命令执行的合理最长时间（毫秒）
    performance.maxTime: 5000

spring:
    profiles.active: @profileActive@
#    output.ansi.enabled: always
    aop.proxy-target-class: true
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
        cache: false
        gzipped: true
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: myuser
      password: mypassword
      # tomcat-jdbc专用配置
      tomcat:
        max-active: 20
        max-idle: 10
        min-idle: 1
        test-on-borrow: true
        test-while-idle: true
        validation-query: select 1
    thymeleaf:
      # 静态资源热部署，而不是缓存
      cache: false
      mode: LEGACYHTML5
      prefix: classpath:/static/template
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8